export const LanguageList = {
    " select language":"ln",
    "English": "en",
    "Hindi": "hi",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Chinese": "zh",
    "Russian": "ru",
    "Arabic": "ar",
    "Portuguese": "pt",
    "Japanese": "ja",
    "Italian": "it",
    "Dutch": "nl",
    "Korean": "ko",
    "Turkish": "tr",
    "Polish": "pl",
    "Swedish": "sv",
    "Danish": "da",
    "Norwegian": "no",
    "Finnish": "fi",
    "Greek": "el",
    "Czech": "cs",
    "Hungarian": "hu",
    "Romanian": "ro",
    "Thai": "th",
    "Swahili": "sw",
    "Ukrainian": "uk",
    "Hebrew": "he",
    "Bengali": "bn",
    "Tamil": "ta",
    "Telugu": "te",
    "Gujarati": "gu",
    "Malayalam": "ml",
    "Punjabi": "pa",
    "Marathi": "mr"
};
